import Image from "next/image";
import Section1 from "./components/section1";
import Section2 from "./components/section2";
import Section3 from "./components/section3";

export const metadata = {
  title: "Next Tailwind",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Section1 />
      <Section2 />
      <Section3 />
    </div>
  );
}
